# Generated by Django 2.2.6 on 2019-11-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='covers/default.jpg', upload_to='covers'),
        ),
    ]
